name: GSThieving
main: com.bukkit.FlingeR.PickPocket.PickPocket
version: 0.3
version comment: Forked from FlingeR's Github, implemented into GuardianScrolls
website: http://www.opentz.com.ar/MinecraftProjects/?page_id=90
author: MeneXia